### ISSUE TITLE
Install but not working

### ISSUE THREAD

**Issue by R00T88** [loitho/Docker-Nagios-Nagvis-Nagiosgraph#1]
Hello,
i install ubuntu 14:04 x64 with LAMP.
Install docker e run docker run -d -p 80:80 loitho/nag-ios-vis-graph
it's say port 80 already in use and not working

**Comment by loitho** [comment]
Hi, that's because your LAMP stack most likely has web server running on the port 80. either disable the web server, or use another port than the 80. You can do that by changing "-p 80:80" to something like "-p 90:80" now you should be able to connect through the port 90

Edit : I've modified the readme file so that it's a bit more clear on how you can run the file
